### ISSUE TITLE
UI Checklist

### ISSUE THREAD

**Issue by VyPham23** [mezonai/mezon#83]
**Default UI**

- [ ] Verify that the selected element like channel/message/menu option... is highlighted and corresponds to the correct URL
- [ ] Check that all elements on the feature are adequately displayed
- [ ] Check for the default selected option in dropdown items
- [ ] Verify the correct placeholder on the search bar
- [ ] Verify the disabled/enabled states of buttons, radio buttons, and checkboxes
- [ ] Check for spelling errors in elements such as titles, explanatory texts, and labels
- [ ] Check for the changes of cursor for each element
- [ ] Verify that the URL are clickable
- [ ] Verify that all elements are displayed as UI design: layout, color, font size, alignment

**Modals**
- [ ] Verify that negative option (No, Cancel,...) is on the left and positive option (Yes, OK, {take action},...) is on the right

**Buttons**

📑 Click Effect:
- [ ] Check for proper redirection or execution of the intended function
- [ ] Verify that the button changes states appropriately (enabled or disabled) based on the application's logic or user input
- [ ] Verify that the text on the button accurately represents the action it performs

📑 Hover Effect:
- [ ] Hover over the button and confirm that any hover effects are applied correctly
- [ ] Verify that users receive visual feedback when interacting with the button

**Search bars**

📑 Valid Search Query
- [ ] Enter a valid search query and verify that relevant results are displayed
- [ ] Verify that relevant autocomplete suggestions appear as the user types
- [ ] Test selecting a suggestion to perform the search
- [ ] Verify that the returned result matches the searched item
 
📑 Invalid Search Query/ Special Characters:
- [ ] Verify that an appropriate error message is displayed

📑 Clear Search Field
- [ ] Click the clear or 'X' button, and verify that the search field is cleared

**Tooltips**

- [ ] Hover Trigger: Hover over elements with tooltips and confirm that tooltip text appears correctly

**Input Fields**

- [ ] Make sure that input error messaging associated with the input it corresponds to
- [ ] Make sure that form input errors are displayed in list above the form after submission
